### PR TITLE
config for song select laser speed

### LINKED ISSUE #26: Can not browse song list with knobs
Since the lastest update, d80700dc82a54d053bbf2edf0f230f4e36cada9e (possibly introduced further back, I jumped from f3a3937bd5d4cd7775fa2c2751cbd8189b1a080f to there), I'm unable to navigate the song list with the knobs on my controller. It just pretends to be a keyboard and sends the letters q and w or o and p for each knob and direction.

Doesn't work with the keyboard either, I have to use the arrow keys instead.

### PR DESCRIPTION
**Pull request by ubuntor**
Adds config option for how fast song/difficulty select with lasers is. Fixes #26.

### CODE REVIEW

**Comment by Dan9er** [comment]
Holy **** @ubuntor, that was fast!

**Comment by Drewol** [comment]
While this option is probably good to have I'm not sure if it fixes #26 I'm also not sure about the name of the option as it's a multiplier on top of the existing sensitivity and the default should also probably be 1.

**Comment by ubuntor** [comment]
What about SongSelectLaserSensitivity?

**Comment by Dan9er** [comment]
@Drewol Bump?

**Comment by Drewol** [comment]
Closing as the relevant issue was fixed.

**Pull request closed without merging**
