### PR TITLE
More background/foreground lua customisation

### PR DESCRIPTION
**Pull request by Jirinrin**
This PR allows lua to make the game load a different background image for gameplay each time, so that a skin can have different "gameplay themes" that might change based on difficulty, skin config, randomness...

By the way I'm not experienced at all with C++ and the like, so forgive me if I made any stupid mistakes :>

Lastly a random comment: maybe it's good to also return the path to a shader for the background/foreground?

### CODE REVIEW

**Comment by Drewol** [comment]
So there's a few things here that I think should work differently, while I think that the skin having more control over the BG is good your implementation is not completely compatible with how I think the BG skinning should work. First I think that the most important BG upgrade is making new default backgrounds that correspond to each of the ksh backgrounds (Arrows, Smoke, Wave, Techno, Snow, and Sakura storm). I also think that just changing the texture is not enough for a lot of backgrounds, the fragment shader should also be possible to change.

I'm not really sure why you've placed the related lua functions in the gameplay lua as well since it doesn't seem necessary to load that entire file once more when only two set fuctions are to be used, if there's a good reason for them to be in lua then can't the background and gameplay just share lua context?

**Comment by Jirinrin** [comment]
Kyaaa OP commented (๑>ᴗ<๑) (hehe this is my first open source contribution thingy so yeah~~~)

In order:
1. Ooh this is actually a very good point! I didn't even know/realise that ksh maps already implement this. 
=> As you're saying, telling Background.cpp to do something with the 'bg' and 'layer' keys in case it doesn't point to a .fs file is probably more than enough of a first step -- for that I'll try to come up with an elegant way to allow skins to implement these backgrounds and foregrounds separately (and if the skin doesn't implement a certain keyword, falling back to the normal bg_texture.png and fg_texture.png should be sufficient)(not sure yet whether lua is still a necessary for that)
(Side comment: some skins have custom background videos, (and things like hitsounds) do you have any plans for that?)
2. Yeah I was already fearing that it wouldn't be robust enough when you can't control the fragment shader file... In the new approach I'll incorporate it! (Probably just returning a tuple in lua or something)
3. I put the lua functions in the gameplay file because I wanted them to be able to access the 'gameplay' table but, ehh yeah of course it doesn't work that way because it's global Σ(´∀｀；) so point taken

**Comment by Drewol** [comment]
I started my own background rework at https://github.com/Drewol/unnamed-sdvx-clone/tree/bg-rework that mostly works in a way that I think would be good, right now all the backgrounds are just duplicates of the old one so I could use some help writing new ones that correspond to the ksm ones.

**Comment by Drewol** [comment]
Closing this since I've merged my own bg rework.

**Pull request closed without merging**
