### PR TITLE
Cleaned up and updated README.md a lot

### PR DESCRIPTION
**Pull request by Dan9er**
- Added:
  - "Skinning support" to features list
  - "Fix linux support" to TODO list
- Removed:
  - Unnecessary backslashes on '*.ksh'
  - Unnecessary whitespace in 'Controls'
- Changed SDVX link
- Rephrased "Real time FX" in features list
- Reformated "Main.cfg" paragraphs
- Made command text smaller to fit in one line in web view
- Moved "Not reqiured to build from source" from 'How to build' to 'Windows' (There's no pre-built exe for Linux... yet!)
- Escaped backslash on line 67/71 (Visual Studio)
- Spelling and grammar

### CODE REVIEW

**Comment by Dan9er** [comment]
@Drewol Because you said before that Linux support is broken...

**Comment by Drewol** [comment]
Well I fixed that almost a month ago 16f2cbae2f32112d6fdb0db2956d824340815199

**Comment by Dan9er** [comment]
Oh shit, sorry

**Comment by Dan9er** [comment]
(Git iz hard .-.)

**Pull request merged**
