### PR TITLE
Make immutable array const

### PR DESCRIPTION
**Pull request by Hinara**

### CODE REVIEW

**Comment by Drewol** [comment]
I can't get this to compile (windows, vs2022) due to line 61 in Material.cpp:

```cpp
	// Defined in Shader.cpp
	extern uint32 shaderStageMap[];
```

just adding const to that doesn't solve it so I'll have to look into it more or just move some things around

**Comment by RobinMEPITECH** [comment]
Should do the tricks, works under linux, is it okay on the windows side ?

**Comment by Hinara** [comment]
Shoud be good now, does it work under windows ?

**Comment by Drewol** [comment]
yes that seems to have done it, lgtm

**Pull request merged**
