### PR TITLE
Add barebones Editor files and attempt to install Squirrel

### PR DESCRIPTION
**Pull request by nashiora**
Project files are generated fine for Squirrel but I can't figure out how to get the includes visible to e.g. Main, the project still compiles and runs regardless.

### CODE REVIEW

**Comment by nashiora** [comment]
Creating new pull request with the finished changes since this hasn't been accepted yet

**Comment by nashiora** [comment]
That feel when you're like "it wants me to open a new one" and then it actually doesn't because you don't know how this works.

**Comment by jerwuqu** [comment]
This is ultimately up to Drewol but I'm just gonna give some thoughts.

1. There are over 17k lines changed which makes this PR very hard to look through.
2. Why is the editor and the Squirrel addition in the same PR? Are they related somehow?
3. I propose naming the `Script` class `SquirrelScript` instead for clarification.
4. Why did you add `/bin` to `.gitignore`? There are files in the `bin` folder.

Too much stuff in here

**Comment by nashiora** [comment]
I've been talking with Drewol the whole time writing this, and yes I know this is a huge PR.

I can revert the `/bin` addition, I didn't realize I had done that.

The editor changes and the script additions are in the same branch because I don't collab on git/hub really at all so I'm very used to my own single-branch work environment and completely forgot to switch to a new one until I'd made the changes.

There are so many new lines to the PR because the squirrel library was added, changes to the actual source of USC are minor otherwise.

The base Script class is named as such because I'm not sure if we want to stick with Squirrel, I just pushed to try it out because I liked it in the past. The implementation can be renamed to be better, but Script itself should ideally be designed to not care that Squirrel is used at all.

I've been asking to merge this PR to get it all fixed and over with for a few days, I know it's a shitstorm trust me, Drewol has even already pulled and built on a Linux machine to test that it all works there as well.

I had a lot of learning and adapting to do as far as the code base, the build tools, and the quirks of C++ that I've long since forgotten, so a bit much happened. Future changes will all be as manageable as I can make them, I just had a hell of a time setting this up in the first place.

**Comment by nashiora** [comment]
After having written this I also think it shouldn't be merged yet. I'll likely just close this, completely re-do my branches and go ahead and make the commits much smaller.

**Pull request closed without merging**
