### PR TITLE
Added VOLFORCE feature

### PR DESCRIPTION
**Pull request by atty303**
Added VOLFORCE calculation to core and export values to Lua.
The formula is based on below.
http://bemaniwiki.com/index.php?SOUND%20VOLTEX%20VIVID%20WAVE/VOLFORCE

This feature will motivate to play this game :smile:

### CODE REVIEW

**Comment by Drewol** [comment]
Looks good but I think maybe the calculation should be customizable in some way as it has changed between sound voltex version and maybe someone would like to do a completely different algorithm as well

**Comment by atty303** [comment]
@Drewol I moved the force calculations to lua. Is this OK?

**Comment by Drewol** [comment]
While the performance impact doesn't seem to be noticable I would prefer a version where it doesn't update `allSongs` and re-calculates the force value when you change filters or use the search field. So that it's only updated when necessary. Other than that it looks good.

**Comment by atty303** [comment]
I have fixed it so as not to make unnecessary updates to `allSongs`.

**Pull request merged**
