### PR TITLE
Allow BUTTON_BCK use in multiplayer and dl screens

### PR DESCRIPTION
**Pull request by Paoda**
Currently, pressing BUTTON_BCK does not do anything when in the multiplayer or song download screens. I found this to be a bit unusual.

This pull request makes it so that BUTTON_BCK is bound to perform the same behavior as pressing escape on the keyboard. 

A consequence of this is that with the default bindings, pressing Escape from the multiplayer / song download screens will exit the game. I believe this is because by default, Button_BCK is bound to Escape, so two "exit" routines are queued to be performed. 

This could be resolved by not binding Escape to BUTTON_BCK by default.

Thank you for working on this project in your free time.

### CODE REVIEW

**Comment by Drewol** [comment]
Could the double back issue be resolved by removing the `key_pressed` entirely? I don't really see why they should be kept.

**Comment by Paoda** [comment]
It could be resolved by removing the `key_pressed`, however I assumed the intention to be that `Esc` always be accessible, like a global shortcut almost. 

I'd imagine if `BUTTON_BCK` is either unset or mistakenly set to something the user doesn't know about, We'd still want the user to be able to go back a screen.

**Comment by Drewol** [comment]
The dl and multi screen scripts were made before the dedicated back button was implemented, the other screens in the game also almost only use the back button now.

**Comment by Paoda** [comment]
Thanks for the clarification. I will remove `key_pressed` then.

**Comment by Paoda** [comment]
The issue I mentioned has now been resolved.

**Comment by itszn** [comment]
Superseded by eef36f869c952044cf9db0bb7998917756a86b5e (which has cpp changes to make back button work correctly in all multi screens)

**Pull request closed without merging**
